# Generated by Django 6.1 on 2026-08-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ussdsession',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='ussdsession',
            name='network_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ussdsession',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ussdsession',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterModelTable(
            name='ussdsession',
            table='ussd_sessions',
        ),
    ]
