# Generated by Django 6.1 on 2026-08-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ussdsession_options_ussdsession_network_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussdlog',
            name='response_type',
            field=models.CharField(default='CON', max_length=10),
        ),
        migrations.AlterModelTable(
            name='ussdlog',
            table='ussd_logs',
        ),
    ]
