# Generated by Django 6.1 on 2026-08-07 15:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ussdlog_response_type_alter_ussdlog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussdsession',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TIMED_OUT', 'Timed Out')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='InterestedFarmer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('buying_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_farmers', to='core.buyingrequest')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_interests', to='core.farmer')),
            ],
            options={
                'db_table': 'interested_farmers',
                'ordering': ['-created_at'],
                'unique_together': {('buying_request', 'farmer')},
            },
        ),
    ]
