# Generated by Django 6.1 on 2026-08-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ussdsession_status_interestedfarmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude ya eneo la mkulima', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude ya eneo la mkulima', max_digits=9, null=True),
        ),
    ]
