# Generated by Django 6.1 on 2026-08-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_farmer_last_location_update_farmer_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_unit',
            field=models.CharField(default='kg', max_length=20),
        ),
    ]
