# Generated by Django 6.1 on 2026-08-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_quantity_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='district',
            field=models.CharField(blank=True, help_text='Wilaya ya supplier', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude ya eneo la supplier', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude ya eneo la supplier', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='region',
            field=models.CharField(blank=True, help_text='Mkoa wa supplier', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='village',
            field=models.CharField(blank=True, help_text='Kijiji cha supplier', max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='ward',
            field=models.CharField(blank=True, help_text='Kata ya supplier', max_length=100),
        ),
    ]
