# Generated by Django 6.1 on 2026-08-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_supplier_district_supplier_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='has_bank_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='has_saccos_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='is_loan_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='loan_eligibility_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmer',
            name='loan_eligibility_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='previous_loan_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='saccos_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='farmer',
            name='years_farming',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
