# Generated by Django 6.1 on 2026-08-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_farmer_bank_name_farmer_has_bank_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='credit_readiness_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmer',
            name='estimated_production',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated production in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farm_ownership',
            field=models.CharField(blank=True, choices=[('OWNED', 'Owned'), ('RENTED', 'Rented'), ('BOTH', 'Both')], max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='has_mobile_money',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='irrigation_type',
            field=models.CharField(blank=True, choices=[('RAIN_FED', 'Rain-fed'), ('IRRIGATION', 'Irrigation'), ('BOTH', 'Both')], max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='last_activity_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='loan_eligibility_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='mobile_money_provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='farmer',
            name='production_season',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='farmer',
            name='profile_completeness',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmer',
            name='total_market_transactions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmer',
            name='total_orders_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmer',
            name='total_orders_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='farmer',
            name='total_sales_estimate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
