# Generated by Django 5.0.14 on 2026-08-21 16:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_farmer_credit_readiness_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under review'), ('INFO_REQUIRED', 'Information required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed'), ('REPAID', 'Repaid'), ('DEFAULTED', 'Defaulted')], default='DISBURSED', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoanDecisionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.CharField(max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('principal_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interest_due', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='DUE', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='loanapplication',
            options={},
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='decision_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_application', to='core.order'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_loan_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='eligibility_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='loan_type',
            field=models.CharField(default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='minimum_credit_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='repayment_frequency',
            field=models.CharField(default='MONTHLY', max_length=20),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='required_profile_information',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under review'), ('INFO_REQUIRED', 'Information required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed'), ('REPAID', 'Repaid'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('LOAN_PENDING', 'Loan pending'), ('PAYMENT_PENDING', 'Payment pending'), ('SUPPLIER_PAID', 'Supplier paid'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='loanapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'UNDER_REVIEW', 'INFO_REQUIRED', 'APPROVED'])), fields=('farmer', 'loan_product'), name='one_active_application_per_product'),
        ),
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='core.loanapplication'),
        ),
        migrations.AddField(
            model_name='loandecisionaudit',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_audits', to='core.loanapplication'),
        ),
        migrations.AddField(
            model_name='loandecisionaudit',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_decision_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repayment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='core.loan'),
        ),
    ]
