# Generated by Django 5.0.14 on 2026-08-21 17:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_loan_loandecisionaudit_repayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(default='MANUAL_INSTRUCTION', max_length=40)),
                ('provider_reference', models.CharField(max_length=120, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('PAYMENT_INITIATED', 'Payment initiated'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_CONFIRMED', 'Payment confirmed'), ('PAYMENT_FAILED', 'Payment failed')], default='PAYMENT_INITIATED', max_length=25)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='repayment',
            options={},
        ),
        migrations.AddField(
            model_name='repayment',
            name='installment_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repayment',
            name='total_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='event_key',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('DUE', 'Due'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], default='UPCOMING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='repayment',
            constraint=models.UniqueConstraint(fields=('loan', 'installment_number'), name='unique_loan_installment'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='core.loan'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='repayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='core.repayment'),
        ),
    ]
