# Generated by Django 6.1 on 2026-08-21 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_paymenttransaction_alter_repayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='loan_type',
            field=models.CharField(choices=[('GENERAL', 'Mkopo wa Jumla'), ('INPUT', 'Mkopo wa Pembejeo'), ('PRODUCTION', 'Mkopo wa Uzalishaji'), ('MARKET', 'Mkopo wa Biashara ya Mazao')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='minimum_credit_score',
            field=models.PositiveIntegerField(default=40, help_text='Minimum credit readiness score required (0-100)'),
        ),
        migrations.AlterField(
            model_name='loanproduct',
            name='repayment_frequency',
            field=models.CharField(choices=[('WEEKLY', 'Kila Wiki'), ('BIWEEKLY', 'Kila Wiki Mbili'), ('MONTHLY', 'Kila Mwezi'), ('QUARTERLY', 'Kila Robo Mwaka')], default='MONTHLY', max_length=20),
        ),
    ]
