# Generated by Django 5.0.14 on 2026-08-22 07:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_loanproduct_loan_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDisbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(max_length=60)),
                ('idempotency_key', models.CharField(max_length=120, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=120, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('recipient', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('provider_result', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='loanapplication',
            name='one_active_application_per_product',
        ),
        migrations.AddField(
            model_name='farmer',
            name='kyc_provider',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='farmer',
            name='kyc_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='farmer',
            name='kyc_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='farmer',
            name='kyc_status',
            field=models.CharField(blank=True, choices=[('PROVIDED', 'NIDA provided'), ('FORMAT_VALID', 'NIDA format valid'), ('VERIFIED', 'Identity verified'), ('FAILED', 'Identity verification failed'), ('PENDING', 'Verification pending')], max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='payout_account_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='acceptance_session_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='acceptance_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='accepted_terms_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under review'), ('INFO_REQUIRED', 'Information required'), ('APPROVED', 'Approved'), ('FARMER_ACCEPTED', 'Farmer accepted'), ('FARMER_DECLINED', 'Farmer declined'), ('DISBURSEMENT_PENDING', 'Disbursement pending'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('PARTIALLY_REPAID', 'Partially repaid'), ('OVERDUE', 'Overdue'), ('FULLY_REPAID', 'Fully repaid'), ('REPAID', 'Repaid'), ('DEFAULTED', 'Defaulted')], default='DISBURSEMENT_PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under review'), ('INFO_REQUIRED', 'Information required'), ('APPROVED', 'Approved'), ('FARMER_ACCEPTED', 'Farmer accepted'), ('FARMER_DECLINED', 'Farmer declined'), ('DISBURSEMENT_PENDING', 'Disbursement pending'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('PARTIALLY_REPAID', 'Partially repaid'), ('OVERDUE', 'Overdue'), ('FULLY_REPAID', 'Fully repaid'), ('REPAID', 'Repaid'), ('DEFAULTED', 'Defaulted')], default='PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PAYMENT_INITIATED', 'Payment initiated'), ('PAYMENT_PENDING', 'Payment pending'), ('PAYMENT_CONFIRMED', 'Payment confirmed'), ('PAYMENT_FAILED', 'Payment failed'), ('PAYMENT_REVERSED', 'Payment reversed')], default='PAYMENT_INITIATED', max_length=25),
        ),
        migrations.AddConstraint(
            model_name='loanapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'UNDER_REVIEW', 'INFO_REQUIRED', 'APPROVED', 'FARMER_ACCEPTED', 'DISBURSEMENT_PENDING'])), fields=('farmer', 'loan_product'), name='one_active_application_per_product'),
        ),
        migrations.AddField(
            model_name='loandisbursement',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement', to='core.loanapplication'),
        ),
        migrations.AddField(
            model_name='loandisbursement',
            name='loan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement', to='core.loan'),
        ),
    ]
